### PR TITLE
Fix and simplify preprocessing and postprocessing

### PR DESCRIPTION
**Pull request by superleesa**
- [x] change preprocessing implementation to torchvision.transforms.v2
- [x] split functions and classes between paired / unpaired
- [x] use cv2, not PIL (#11 )
- [x] implement postprocessing as torchvision.transforms
- [x] debug

### CODE REVIEW

**Comment by superleesa** [comment]
@shoko321 can you do step 4 ~ ?

**Comment by superleesa** [comment]
By the way, I split the create_dataset function into create_paired_dataset and create_unpaired_dataset because there wasn't really any meaning in combining the two features into one.

**Comment by sho-asn** [comment]
Okay. They are debug, implement postprocessing as torchvision.transforms and debug right? what does postprocessing mean by in this context?

**Comment by superleesa** [comment]
Yes. For the postprocessing, it's basically this part that we want to modularize:
https://github.com/superleesa/final_year_project/blob/e276c38e6e8338b57c4518c830bd157fb7cde8aa/validate.py#L51-L53

**Comment by sho-asn** [comment]
@superleesa 
```
if save_images == "all":
                # denoised_images = denoised_images.cpu().numpy()
                # denoised_images = np.transpose(denoised_images, axes=[0, 2, 3, 1]).astype('float32')
                # denoised_images = np.clip(denoised_images*255, 0.0, 255.0)  # normalize back to 0~255
                denoised_images = validate_transform(denoised_images)
                for denoised_image, image_name in zip(denoised_images, image_names):
                    save_image(denoised_image, image_name, save_dir)
            
            elif save_images == "sample":
                image_idx = random.randint(0, len(denoised_images)-1)
                denoised_image, image_name = denoised_images[image_idx], image_names[image_idx]
                save_image(denoised_image, image_name, save_dir)
```
why didn't you do post-process in the case of save_images == "sample"? Do we need the post-process for it as well right?

**Comment by superleesa** [comment]
I think I simply forgot to add it... could you add it please?

**Comment by sho-asn** [comment]
@superleesa 
I pushed and committed.

**Comment by superleesa** [comment]
@shoko321 can you quickly change the name of function from validate_transforms to postprocess?

**Comment by superleesa** [comment]
todo: rename validate.py to evaluate.py

**Pull request merged**
