### PR TITLE
added code for VIF metric

### PR DESCRIPTION
**Pull request by wiinnie9**

### CODE REVIEW

**Comment by wiinnie9** [comment]
created pull request for fork repo to add the VIF code for metrics

**Comment by superleesa** [comment]
because the input comes in torch.Tensor format but you use numpy in the code, i think it's better if we convert the input into np.ndarray at the beginning of the function?

**Comment by superleesa** [comment]
I read the original paper now and started to think that this metric cannot be used for our purposes...

This metric computes how an image is degraded from noise. It compares a clean image vs. a degraded sand-storm image. However, we want to compare a **clean image vs. a restored image from the model**. 

Also, it uses HSV. Given an input image, it extracts only the information in the image that the brain can understand (so it assumes that when humans see images/scenery, there is some loss of information). but I feel that this is unnecessary lol (we can simply compare actual images, assuming that there is no loss of information).

image

[link to original paper ](https://ieeexplore.ieee.org/document/1576816)

**Comment by wiinnie9** [comment]
I see. I do agree with this part where I saw a source that states that _"Visual Information Fidelity (VIF) [152] is able to measure the loss of information in the original image caused by the processing or transmission of the input image"_, which matches what you said earlier on the clean image vs degraded image. I think we could abandon this for now unless we find a situation that we could use it in the future, meanwhile I'll look on more metrics as suggested.

**Pull request closed without merging**
